[package]
name        = "app"
version     = "1.0.0"
description = "Katika Desktop App"
authors     = ["Katika <contact@katika.cm>"]
edition     = "2021"
rust-version = "1.77.2"

[lib]
name = "app_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2.5.4", features = [] }

[dependencies]
serde_json = "1.0"
serde      = { version = "1.0", features = ["derive"] }
log        = "0.4"
tauri      = { version = "2.10.0", features = [] }
tauri-plugin-log     = "2"
tauri-plugin-opener  = "2"
tauri-plugin-http    = "2"
tauri-plugin-shell   = "2"
tauri-plugin-fs      = "2"
tauri-plugin-notification = "2"
